## LATIHAN

## 1.Perkalian Matrix

In [6]:
import numpy as np

A = np.array([30, 12, 4])
B = np.array([98, 22, 68])

perkalian = A * B
print(perkalian)

[2940  264  272]


## 2.Pengurangan Matrix

In [5]:
import numpy as np

A = np.array([30, 12, 4])
B = np.array([98, 22, 6])
              
pengurangan = A - B
print(pengurangan)

[-68 -10  -2]


## 3.Transpose Matrix

In [4]:
import numpy as np

A = np.array([30, 12, 4])
B = np.array([98, 22, 6])

transpose_A = np.transpose(A) 
print(transpose_A)

[30 12  4]


## 4.Nilai Invers

In [8]:
A = np.array([[3,2], [2,3]])

inverse_A = np.linalg.inv(A)
print("\ninvers matriks A:")
print(inverse_A)


invers matriks A:
[[ 0.6 -0.4]
 [-0.4  0.6]]


## 5.Nilai Determinan

In [9]:
import numpy as np

A = np.array([[3,2], [2,3]])

determinant_A = np.linalg.det(A)
print("Determinan dari matriks A:", determinant_A)

Determinan dari matriks A: 5.000000000000001
